### ISSUE TITLE
是不是不能用了？11月21号21点之后就再也不能同步了

### ISSUE THREAD

**Issue by bunnyml** [ghosx/qcloud_ddns#2]
控制台报错内容

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dnsapi.cn', port=443): Max retries exceeded with url: /Record.List (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xffff8ae28d68>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by ghosx** [comment]
这个报错是网络问题，请先检查自己的网络是否正常

**Comment by bunnyml** [comment]
好的。我再检查检查，在本地windows运行main.py一切正常，应该是我debian主机的问题。
